version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  default:
    working_directory: ~/dark_wood_pile
    docker:
      - image: cimg/ruby:3.0.3-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:13.4-ram

    steps:
      - checkout
      - ruby/install-deps

      - run:
          name: Update Chrome
          command: bundle exec rake webdrivers:chromedriver:update

      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup database
          command: cp .circleci/database.yml config/database.yml && bundle exec rake db:create db:migrate

      - run:
          name: Run tests
          command: bundle exec rake

workflows:
  version: 2
  default:
    jobs:
      - default
